sudo: required

language: cpp

git:
  submodules: false

services:
  - docker
  
before_install:
  - docker pull esrfbliss/lima-ci-debian8
  - docker run --name lima-ci-docker -v $(pwd):/src-ci/ -dit esrfbliss/lima-ci-debian8
  
script:  
  - echo "Unset esrf proxy from docker and cloning GitHub repositories"
  - docker exec lima-ci-docker /bin/sh -c 'unset https_proxy && unset http_proxy && cd /root && ./install_lima_submodule'
  
  - echo "copy the camera code from the pull request"
  - docker exec lima-ci-docker /bin/sh -c 'cd /root/Lima/camera/eiger && cp -R /src-ci/* .'
  
  - echo "Compiling Lima and camera eiger with options"
  - docker exec lima-ci-docker /bin/sh -c 'cd /root/Lima/ && ./install.sh camera/eiger python tests cbf fits tiff hdf5 config'
  
  - echo "Executing tests in build repository"
  - docker exec lima-ci-docker /bin/sh -c 'cd /root/Lima/build/ && ctest --timeout 10'

after-script:
  - docker stop lima-ci-docker
  - docker rm lima-ci-docker
  
branches:
  only:
  - cmake  
